# Generated by Django 3.0.5 on 2020-05-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200503_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='appearance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='damage_bonus',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='durability',
        ),
        migrations.RemoveField(
            model_name='character',
            name='education',
        ),
        migrations.RemoveField(
            model_name='character',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='knowledge',
        ),
        migrations.RemoveField(
            model_name='character',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='character',
            name='magic_point',
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_sanity_point',
        ),
        migrations.RemoveField(
            model_name='character',
            name='power',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sanity_point',
        ),
        migrations.RemoveField(
            model_name='character',
            name='size',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=9, verbose_name='STR')),
                ('constitution', models.IntegerField(default=9, verbose_name='CON')),
                ('size', models.IntegerField(default=9, verbose_name='SIZ')),
                ('dexterity', models.IntegerField(default=9, verbose_name='DEX')),
                ('appearance', models.IntegerField(default=9, verbose_name='APP')),
                ('intelligence', models.IntegerField(default=9, verbose_name='INT')),
                ('power', models.IntegerField(default=9, verbose_name='POW')),
                ('education', models.IntegerField(default=12, verbose_name='EDU')),
                ('idea', models.IntegerField(default=50, verbose_name='アイデア')),
                ('luck', models.IntegerField(default=50, verbose_name='幸運')),
                ('knowledge', models.IntegerField(default=50, verbose_name='知識')),
                ('sanity_point', models.IntegerField(default=50, verbose_name='SAN値')),
                ('max_sanity_point', models.IntegerField(default=99, verbose_name='最大正気度')),
                ('magic_point', models.IntegerField(default=9, verbose_name='マジックポイント')),
                ('durability', models.IntegerField(default=9, verbose_name='耐久力')),
                ('damage_bonus', models.CharField(default='0', max_length=10, verbose_name='ダメージ・ボーナス')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Character', verbose_name='キャラクター')),
            ],
        ),
    ]
