# Generated by Django 3.0.5 on 2020-05-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200503_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='damage_bonus',
            field=models.IntegerField(default=0, max_length=10, verbose_name='ダメージ・ボーナス'),
        ),
    ]
