# Generated by Django 3.0.5 on 2020-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200503_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='damage_bonus',
            field=models.CharField(choices=[('0', '0'), ('-1D6', '-1D6'), ('-1D4', '-1D4'), ('1D4', '1D4'), ('1D6', '1D6')], default='0', max_length=10, verbose_name='ダメージ・ボーナス'),
        ),
    ]
