# Generated by Django 3.0.5 on 2020-05-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200503_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cms/', verbose_name='添付画像'),
        ),
    ]
