# Generated by Django 3.0.5 on 2020-05-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_character_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deception', models.IntegerField(default=5, verbose_name='言いくるめ')),
                ('medicine', models.IntegerField(default=5, verbose_name='医学')),
                ('driving', models.IntegerField(default=20, verbose_name='運転')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cms.Character', verbose_name='キャラクター')),
            ],
        ),
    ]
