# Generated by Django 3.0.5 on 2020-05-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_normalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalskill',
            name='avoidance',
            field=models.IntegerField(default=21, verbose_name='回避'),
        ),
        migrations.AddField(
            model_name='normalskill',
            name='first_aid',
            field=models.IntegerField(default=30, verbose_name='応急手当'),
        ),
        migrations.AddField(
            model_name='normalskill',
            name='occult',
            field=models.IntegerField(default=5, verbose_name='オカルト'),
        ),
    ]
