# Generated by Django 3.0.5 on 2020-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20200509_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='freespace',
            field=models.TextField(blank=True, null=True, verbose_name='自由記入欄'),
        ),
        migrations.AddField(
            model_name='chara',
            name='original_skill',
            field=models.TextField(blank=True, null=True, verbose_name='オリジナル技能'),
        ),
    ]
