# Generated by Django 3.0.6 on 2020-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200510_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='chara',
            name='accounting',
            field=models.IntegerField(default=10, verbose_name='経理'),
        ),
        migrations.AddField(
            model_name='chara',
            name='anthropology',
            field=models.IntegerField(default=1, verbose_name='人類学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='archaeology',
            field=models.IntegerField(default=1, verbose_name='考古学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='art',
            field=models.IntegerField(default=5, verbose_name='芸術'),
        ),
        migrations.AddField(
            model_name='chara',
            name='astronomy',
            field=models.IntegerField(default=1, verbose_name='天文学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='biology',
            field=models.IntegerField(default=1, verbose_name='生物学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='budo',
            field=models.IntegerField(default=1, verbose_name='武道'),
        ),
        migrations.AddField(
            model_name='chara',
            name='chase',
            field=models.IntegerField(default=10, verbose_name='追跡'),
        ),
        migrations.AddField(
            model_name='chara',
            name='chemistry',
            field=models.IntegerField(default=1, verbose_name='化学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='climbing',
            field=models.IntegerField(default=40, verbose_name='登坂'),
        ),
        migrations.AddField(
            model_name='chara',
            name='computer',
            field=models.IntegerField(default=1, verbose_name='コンピューター'),
        ),
        migrations.AddField(
            model_name='chara',
            name='cthulhu_mythos',
            field=models.IntegerField(default=0, verbose_name='クトゥルフ神話'),
        ),
        migrations.AddField(
            model_name='chara',
            name='discount',
            field=models.IntegerField(default=5, verbose_name='値切り'),
        ),
        migrations.AddField(
            model_name='chara',
            name='disguise',
            field=models.IntegerField(default=1, verbose_name='変装'),
        ),
        migrations.AddField(
            model_name='chara',
            name='electrical_repair',
            field=models.IntegerField(default=10, verbose_name='電気修理'),
        ),
        migrations.AddField(
            model_name='chara',
            name='electronics',
            field=models.IntegerField(default=1, verbose_name='電子工学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='eye_star',
            field=models.IntegerField(default=25, verbose_name='目星'),
        ),
        migrations.AddField(
            model_name='chara',
            name='geology',
            field=models.IntegerField(default=1, verbose_name='地質学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='handgun',
            field=models.IntegerField(default=20, verbose_name='拳銃'),
        ),
        migrations.AddField(
            model_name='chara',
            name='heading',
            field=models.IntegerField(default=10, verbose_name='頭突き'),
        ),
        migrations.AddField(
            model_name='chara',
            name='heavy_machine_operation',
            field=models.IntegerField(default=1, verbose_name='重機械操作'),
        ),
        migrations.AddField(
            model_name='chara',
            name='hidden',
            field=models.IntegerField(default=10, verbose_name='隠れる'),
        ),
        migrations.AddField(
            model_name='chara',
            name='hide',
            field=models.IntegerField(default=15, verbose_name='隠す'),
        ),
        migrations.AddField(
            model_name='chara',
            name='history',
            field=models.IntegerField(default=20, verbose_name='歴史'),
        ),
        migrations.AddField(
            model_name='chara',
            name='horse_riding',
            field=models.IntegerField(default=5, verbose_name='乗馬'),
        ),
        migrations.AddField(
            model_name='chara',
            name='iai',
            field=models.IntegerField(default=1, verbose_name='居合'),
        ),
        migrations.AddField(
            model_name='chara',
            name='jumpping',
            field=models.IntegerField(default=15, verbose_name='跳躍'),
        ),
        migrations.AddField(
            model_name='chara',
            name='kick',
            field=models.IntegerField(default=25, verbose_name='キック'),
        ),
        migrations.AddField(
            model_name='chara',
            name='law',
            field=models.IntegerField(default=5, verbose_name='回避'),
        ),
        migrations.AddField(
            model_name='chara',
            name='library',
            field=models.IntegerField(default=25, verbose_name='図書館'),
        ),
        migrations.AddField(
            model_name='chara',
            name='listen',
            field=models.IntegerField(default=25, verbose_name='聞き耳'),
        ),
        migrations.AddField(
            model_name='chara',
            name='machine_repair',
            field=models.IntegerField(default=20, verbose_name='機械修理'),
        ),
        migrations.AddField(
            model_name='chara',
            name='machinegun',
            field=models.IntegerField(default=15, verbose_name='マシンガン'),
        ),
        migrations.AddField(
            model_name='chara',
            name='martial_arts',
            field=models.IntegerField(default=1, verbose_name='マーシャルアーツ'),
        ),
        migrations.AddField(
            model_name='chara',
            name='mother_tongue',
            field=models.IntegerField(default=60, verbose_name='母国語'),
        ),
        migrations.AddField(
            model_name='chara',
            name='natural_history',
            field=models.IntegerField(default=10, verbose_name='博物学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='navigate',
            field=models.IntegerField(default=10, verbose_name='ナビゲート'),
        ),
        migrations.AddField(
            model_name='chara',
            name='nelson_hold',
            field=models.IntegerField(default=25, verbose_name='組みつき'),
        ),
        migrations.AddField(
            model_name='chara',
            name='persuasion',
            field=models.IntegerField(default=15, verbose_name='説得'),
        ),
        migrations.AddField(
            model_name='chara',
            name='pharmacy',
            field=models.IntegerField(default=1, verbose_name='薬学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='photography',
            field=models.IntegerField(default=10, verbose_name='写真術'),
        ),
        migrations.AddField(
            model_name='chara',
            name='physics',
            field=models.IntegerField(default=1, verbose_name='物理学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='picking',
            field=models.IntegerField(default=1, verbose_name='鍵開け'),
        ),
        migrations.AddField(
            model_name='chara',
            name='psychoanalysis',
            field=models.IntegerField(default=1, verbose_name='精神分析'),
        ),
        migrations.AddField(
            model_name='chara',
            name='psychology',
            field=models.IntegerField(default=5, verbose_name='心理学'),
        ),
        migrations.AddField(
            model_name='chara',
            name='punch',
            field=models.IntegerField(default=50, verbose_name='こぶし'),
        ),
        migrations.AddField(
            model_name='chara',
            name='rifle',
            field=models.IntegerField(default=25, verbose_name='ライフル'),
        ),
        migrations.AddField(
            model_name='chara',
            name='shotgun',
            field=models.IntegerField(default=30, verbose_name='ショットガン'),
        ),
        migrations.AddField(
            model_name='chara',
            name='sneaking',
            field=models.IntegerField(default=10, verbose_name='忍び歩き'),
        ),
        migrations.AddField(
            model_name='chara',
            name='submachinegun',
            field=models.IntegerField(default=15, verbose_name='サブマシンガン'),
        ),
        migrations.AddField(
            model_name='chara',
            name='survival',
            field=models.IntegerField(default=10, verbose_name='サバイバル'),
        ),
        migrations.AddField(
            model_name='chara',
            name='swimming',
            field=models.IntegerField(default=25, verbose_name='水泳'),
        ),
        migrations.AddField(
            model_name='chara',
            name='throwing',
            field=models.IntegerField(default=25, verbose_name='投擲'),
        ),
        migrations.AddField(
            model_name='chara',
            name='trust',
            field=models.IntegerField(default=15, verbose_name='信用'),
        ),
    ]
